name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: install dependency
      run: sudo apt install libtirpc-dev libkrb5-dev meson ninja-build

    - name: checkout libfuse3
      uses: actions/checkout@v2
      with:
        repository: libfuse/libfuse
        ref: fuse-3.9.0

    - name: install libfuse3
      shell: bash
      run: |
        mkdir build; cd build
        meson ..
        ninja
        sudo ninja install
        sudo ldconfig

    - name: checkout nfs-fuse
      uses: actions/checkout@v2
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
