name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - run: sudo apt install libtirpc-dev libkrb5-dev libfuse-dev

    - uses: actions/checkout@v2

    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
